name: Build Plugin

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Setup MSVC Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@v1

    - name: Configure
      run: cmake -B build -S . -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build build --config Release

    - name: Rename .dll to .addon64
      shell: pwsh
      run: |
        $dllPath = Get-ChildItem -Path "build/bin" -Recurse -Filter "*.dll" | Select-Object -First 1
        Write-Host "Found DLL at: $($dllPath.FullName)"
        New-Item -ItemType Directory -Path "artifact" -Force
        Copy-Item -Path $dllPath.FullName -Destination "artifact/zoomscope.addon64"

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: zoomscope.addon64
        path: artifact/zoomscope.addon64
        if-no-files-found: error
